server:
  port: 8080

spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    memory:
      mysql:
        enabled: true
      redis:
        host: localhost
        port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
